-- ws-props.lua
-- returns a table of weapon skill properties
-- for aeonic weapons, test:
--   info.ws_props[spell.english].aeonic
--   and S{player.equipment.main,player.equipment.range}:contains(info.ws_props[spell.english].aeonic.weapon)
--   and (buffactive["Aftermath: Lv.1"] or buffactive["Aftermath: Lv.2"] or buffactive["Aftermath: Lv.3"])
-- TODO see if test works in aftercast, or must be precast

-- L2 skillchain loop: (fusion > gravitation > fragmentation > distortion > fusion)
-- L1 fusion:          (liquefaction > impaction)      L1 fragmentation:   (induration > reverberation)
-- L1 gravitation:     (detonation > compression)      L1 distortion:      (transfixion > scission) 
-- L1 openers:
--      liquefaction, detonation     > scission
--      transfixion, scission        > reverberation
--      compression, scission        > detonation
--      scission, impaction          > liquefaction
--      reverberation                > induration
--      induration, reverberation    > impaction
--      compression                  > transfixion
--      transfixion, induration      > compression

info.ws_props = {
    -- great axe
    ["Shield Break"]    = {props={'Impaction'}},
    ["Iron Tempest"]    = {props={'Scission'}},
    ["Sturmwind"]       = {props={'Reverberation','Scission'}},
    ["Armor Break"]     = {props={'Impaction'}},
    ["Keen Edge"]       = {props={'Compression'}},
    ["Weapon Break"]    = {props={'Impaction'}},
    ["Raging Rush"]     = {props={'Induration','Reverberation'}},
    ["Full Break"]      = {props={'Distortion'}},
    ["Steel Cyclone"]   = {props={'Distortion','Detonation'}},
    ["Fell Cleave"]     = {props={'Impaction','Scission','Detonation'}},
    ["Upheaval"]        = {props={'Fusion','Compression'},aeonic={weapon="Chango",sc='Light'}},
    ["Metatron Torment"]= {props={'Light','Fusion'},relic=true},
    ["Ukko's Fury"]     = {props={'Light','Fragmentation'},empy=true},
    ["King's Justice"]  = {props={'Fragmentation','Scission'},mythic=true},
    -- great sword
    ["Hard Slash"]      = {props={'Scission'}},
    ["Power Slash"]     = {props={'Transfixion'}},
    ["Frostbite"]       = {props={'Induration'}},
    ["Freezebite"]      = {props={'Induration','Detonation'}},
    ["Shockwave"]       = {props={'Reverberation'}},
    ["Crescent Moon"]   = {props={'Scission'}},
    ["Sickle Moon"]     = {props={'Scission','Impaction'}},
    ["Spinning Slash"]  = {props={'Fragmentation'}},
    ["Ground Strike"]   = {props={'Fragmentation','Distortion'}},
    ["Herculean Slash"] = {props={'Induration','Impaction','Detonation'}},
    ["Resolution"]      = {props={'Fragmentation','Scission'},aeonic={weapon="Lionheart",sc='Light'}},
    ["Scourge"]         = {props={'Light','Fusion'},relic=true},
    ["Torcleaver"]      = {props={'Light','Distortion'},empy=true},
    ["Dimidiation"]     = {props={'Light','Fragmentation'},mythic=true},
    -- sword
    ["Fast Blade"]      = {props={'Scission'}},
    ["Burning Blade"]   = {props={'Liquefaction'}},
    ["Red Lotus Blade"] = {props={'Liquefaction','Detonation'}},
    ["Flat Blade"]      = {props={'Impaction'}},
    ["Shining Blade"]   = {props={'Scission'}},
    ["Seraph Blade"]    = {props={'Scission'}},
    ["Circle Blade"]    = {props={'Reverberation','Impaction'}},
    ["Spirits Within"]  = {props=nil},
    ["Vorpal Blade"]    = {props={'Scission','Impaction'}},
    ["Swift Blade"]     = {props={'Gravitation'}},
    ["Savage Blade"]    = {props={'Fragmentation','Scission'}},
    ["Sanguine Blade"]  = {props=nil},
    ["Requiescat"]      = {props={'Gravitation','Scission'},aeonic={weapon="Sequence",sc='Darkness'}},
    ["Knights of Round"]= {props={'Light','Fusion'},relic=true},
    ["Chant du Cygne"]  = {props={'Light','Distortion'},empy=true},
    ["Death Blossom"]   = {props={'Fragmentation','Distortion'},mythic=true},
    ["Atonement"]       = {props={'Fusion','Reverberation'},mythic=true},
    ["Expiacion"]       = {props={'Distortion','Scission'},mythic=true},
    -- axe
    ["Raging Axe"]      = {props={'Detonation','Impaction'}},
    ["Smash Axe"]       = {props={'Induration','Reverberation'}},
    ["Gale Axe"]        = {props={'Detonation'}},
    ["Avalanche Axe"]   = {props={'Scission','Impaction'}},
    ["Rampage"]         = {props={'Scission'}},
    ["Calamity"]        = {props={'Scission','Impaction'}},
    ["Mistral Axe"]     = {props={'Fusion'}},
    ["Decimation"]      = {props={'Fusion','Reverberation'}},
    ["Bora Axe"]        = {props={'Scission','Detonation'}},
    ["Ruinator"]        = {props={'Distortion','Detonation'},aeonic={weapon="Tri-edge",sc='Darkness'}},
    ["Onslaught"]       = {props={'Darkness','Gravitation'},relic=true},
    ["Cloudsplitter"]   = {props={'Darkness','Fragmentation'},empy=true},
    ["Primal Rend"]     = {props={'Gravitation','Reverberation'},mythic=true},
    -- polearm
    ["Double Thrust"]   = {props={'Transfixion'}},
    ["Thunder Thrust"]  = {props={'Transfixion','Impaction'}},
    ["Raiden Thrust"]   = {props={'Transfixion','Impaction'}},
    ["Leg Sweep"]       = {props={'Impaction'}},
    ["Penta Thrust"]    = {props={'Compression'}},
    ["Vorpal Thrust"]   = {props={'Reverberation','Transfixion'}},
    ["Skewer"]          = {props={'Transfixion','Impaction'}},
    ["Wheeling Thrust"] = {props={'Fusion'}},
    ["Impulse Drive"]   = {props={'Gravitation','Induration'}},
    ["Sonic Thrust"]    = {props={'Transfixion','Scission'}},
    ["Stardiver"]       = {props={'Gravitation','Transfixion'},aeonic={weapon="Trishula",sc='Darkness'}},
    ["Geirskogul"]      = {props={'Light','Distortion'},relic=true},
    ["Camlann's Torment"]={props={'Light','Fragmentation'},empy=true},
    ["Drakesbane"]      = {props={'Fusion','Transfixion'},mythic=true},
    -- scythe
    ["Slice"]           = {props={'Scission'}},
    ["Dark Harvest"]    = {props={'Reverberation'}},
    ["Shadow of Death"] = {props={'Induration','Reverberation'}},
    ["Nightmare Scythe"]= {props={'Compression','Scission'}},
    ["Spinning Scythe"] = {props={'Reverberation','Scission'}},
    ["Vorpal Scythe"]   = {props={'Transfixion','Scission'}},
    ["Guillotine"]      = {props={'Induration'}},
    ["Cross Reaper"]    = {props={'Distortion'}},
    ["Spiral Hell"]     = {props={'Distortion','Scission'}},
    ["Infernal Scythe"] = {props={'Compression','Reverberation'}},
    ["Entropy"]         = {props={'Gravitation','Reverberation'},aeonic={weapon="Anguta",sc='Darkness'}},
    ["Catastrophe"]     = {props={'Darkness','Gravitation'},relic=true},
    ["Quietus"]         = {props={'Darkness','Distortion'},empy=true},
    ["Insurgency"]      = {props={'Fusion','Compression'},mythic=true},
    -- great katana
    ["Tachi: Enpi"]     = {props={'Transfixion','Scission'}},
    ["Tachi: Hobaku"]   = {props={'Induration'}},
    ["Tachi: Goten"]    = {props={'Transfixion','Impaction'}},
    ["Tachi: Kagero"]   = {props={'Liquefaction'}},
    ["Tachi: Jinpu"]    = {props={'Scission','Detonation'}},
    ["Tachi: Koki"]     = {props={'Reverberation','Impaction'}},
    ["Tachi: Yukikaze"] = {props={'Induration','Detonation'}},
    ["Tachi: Gekko"]    = {props={'Distortion','Reverberation'}},
    ["Tachi: Kasha"]    = {props={'Fusion','Compression'}},
    ["Tachi: Ageha"]    = {props={'Compression','Scission'}},
    ["Tachi: Shoha"]    = {props={'Fragmentation','Compression'},aeonic={weapon="Dojikiri Yasutsuna",sc='Light'}},
    ["Tachi: Kaiten"]   = {props={'Light','Fragmentation'},relic=true},
    ["Tachi: Fudo"]     = {props={'Light','Distortion'},empy=true},
    ["Tachi: Rana"]     = {props={'Gravitation','Induration'},mythic=true},
    -- katana
    ["Blade: Rin"]      = {props={'Transfixion'}},
    ["Blade: Retsu"]    = {props={'Scission'}},
    ["Blade: Teki"]     = {props={'Reverberation'}},
    ["Blade: To"]       = {props={'Induration','Detonation'}},
    ["Blade: Chi"]      = {props={'Impaction'}},
    ["Blade: Ei"]       = {props={'Compression'}},
    ["Blade: Jin"]      = {props={'Detonation','Impaction'}},
    ["Blade: Ten"]      = {props={'Gravitation'}},
    ["Blade: Ku"]       = {props={'Gravitation','Transfixion'}},
    ["Blade: Yu"]       = {props={'Reverberation','Scission'}},
    ["Blade: Shun"]     = {props={'Fusion','Impaction'},aeonic={weapon="Heishi Shorinken",sc='Light'}},
    ["Blade: Metsu"]    = {props={'Darkness','Fragmentation'},relic=true},
    ["Blade: Kamu"]     = {props={'Fragmentation','Compression'},empy=true},
    ["Blade: Hi"]       = {props={'Darkness','Gravitation'},mythic=true},
    -- dagger
    ["Wasp Sting"]      = {props={'Scission'}},
    ["Gust Slash"]      = {props={'Detonation'}},
    ["Shadowstich"]     = {props={'Reverberation'}},
    ["Viper Bite"]      = {props={'Scission'}},
    ["Cyclone"]         = {props={'Detonation','Impaction'}},
    ["Energy Steal"]    = {props=nil},
    ["Energy Drain"]    = {props=nil},
    ["Dancing Edge"]    = {props={'Scission','Detonation'}},
    ["Shark Bite"]      = {props={'Fragmentation'}},
    ["Evisceration"]    = {props={'Gravitation','Transfixion'}},
    ["Aeolian Edge"]    = {props={'Impaction','Scission','Detonation'}},
    ["Exenterator"]     = {props={'Fragmentation','Scission'},aeonic={weapon="Aeneas",sc='Light'}},
    ["Mercy Stroke"]    = {props={'Darkness','Gravitation'},relic=true},
    ["Rudra's Storm"]   = {props={'Darkness','Distortion'},empy=true},
    ["Mandalic Stab"]   = {props={'Fusion','Compression'},mythic=true},
    ["Mordant Rime"]    = {props={'Fragmentation','Distortion'},mythic=true},
    ["Pyrrhic Kleos"]   = {props={'Distortion','Scission'},mythic=true},
    -- hand-to-hand
    ["Combo"]           = {props={'Impaction'}},
    ["Shoulder Tackle"] = {props={'Reverberation','Impaction'}},
    ["One Inch Punch"]  = {props={'Compression'}},
    ["Backhand Blow"]   = {props={'Detonation'}},
    ["Raging Fists"]    = {props={'Impaction'}},
    ["Spinning Attack"] = {props={'Liquefaction','Impaction'}},
    ["Howling Fist"]    = {props={'Transfixion','Impaction'}},
    ["Dragon Kick"]     = {props={'Fragmentation'}},
    ["Asuran Fists"]    = {props={'Gravitation','Liquefaction'}},
    ["Tornado Kick"]    = {props={'Induration','Impaction','Detonation'}},
    ["Shijin Spiral"]   = {props={'Fusion','Reverberation'},aeonic={weapon="Godhands",sc='Light'}},
    ["Final Heaven"]    = {props={'Light','Fusion'},relic=true},
    ["Victory Smite"]   = {props={'Light','Fragmentation'},empy=true},
    ["Ascetic's Fury"]  = {props={'Fusion','Transfixion'},mythic=true},
    ["Stringing Pummel"]= {props={'Gravitation','Liquefaction'},mythic=true},
    -- staff
    ["Heavy Swing"]     = {props={'Impaction'}},
    ["Rock Crusher"]    = {props={'Impaction'}},
    ["Earth Crusher"]   = {props={'Detonation','Impaction'}},
    ["Starburst"]       = {props={'Compression','Reverberation'}},
    ["Sunburst"]        = {props={'Compression','Reverberation'}},
    ["Shell Crusher"]   = {props={'Detonation'}},
    ["Full Swing"]      = {props={'Liquefaction','Impaction'}},
    ["Spirit Taker"]    = {props=nil},
    ["Retribution"]     = {props={'Gravitation','Reverberation'}},
    ["Cataclysm"]       = {props={'Compression','Reverberation'}},
    ["Shattersoul"]     = {props={'Gravitation','Induration'},aeonic={weapon="Khatvanga",sc='Darkness'}},
    ["Gate of Tartarus"]= {props={'Darkness','Distortion'},relic=true},
    ["Garland of Bliss"]= {props={'Fusion','Reverberation'},mythic=true},
    ["Omniscience"]     = {props={'Gravitation','Transfixion'},mythic=true},
    ["Vidohunir"]       = {props={'Fragmentation','Distortion'},mythic=true},
    ["Myrkr"]           = {props=nil},
    -- club
    ["Shining Strike"]  = {props={'Impaction'}},
    ["Seraph Strike"]   = {props={'Impaction'}},
    ["Brainshaker"]     = {props={'Reverberation'}},
    ["Starlight"]       = {props=nil},
    ["Moonlight"]       = {props=nil},
    ["Skullbreaker"]    = {props={'Induration','Reverberation'}},
    ["True Strike"]     = {props={'Detonation','Impaction'}},
    ["Judgement"]       = {props={'Impaction'}},
    ["Hexa Strike"]     = {props={'Fusion'}},
    ["Black Halo"]      = {props={'Fragmentation','Compression'}},
    ["Flash Nova"]      = {props={'Reverberation','Induration'}},
    ["Realmrazer"]      = {props={'Fusion','Impaction'},aeonic={weapon="Tishtrya",sc='Light'}},
    ["Randgrith"]       = {props={'Light','Fragmentation'},relic=true},
    ["Dagan"]           = {props=nil},
    ["Mystic Boon"]     = {props=nil},
    ["Exudation"]       = {props={'Darkness','Fragmentation'},mythic=true},
    -- archery
    ["Flaming Arrow"]   = {props={'Liquefaction','Transfixion'}},
    ["Piercing Arrow"]  = {props={'Reverberation','Transfixion'}},
    ["Dulling Arrow"]   = {props={'Liquefaction','Transfixion'}},
    ["Sidewinder"]      = {props={'Reverberation','Transfixion','Detonation'}},
    ["Blast Arrow"]     = {props={'Induration','Transfixion'}},
    ["Arching Arrow"]   = {props={'Fusion'}},
    ["Empyreal Arrow"]  = {props={'Fusion','Transfixion'}},
    ["Refulgent Arrow"] = {props={'Reverberation','Transfixion'}},
    ["Apex Arrow"]      = {props={'Fragmentation','Transfixion'},aeonic={weapon="Fail-Not",sc='Light'}},
    ["Namas Arrow"]     = {props={'Light','Distortion'},relic=true},
    ["Jishnu's Radiance"]={props={'Light','Fusion'},empy=true},
    -- marksmanship
    ["Hot Shot"]        = {props={'Liquefaction','Transfixion'}},
    ["Split Shot"]      = {props={'Reverberation','Transfixion'}},
    ["Sniper Shot"]     = {props={'Liquefaction','Transfixion'}},
    ["Slug Shot"]       = {props={'Reverberation','Transfixion','Detonation'}},
    ["Blast Shot"]      = {props={'Induration','Transfixion'}},
    ["Heavy Shot"]      = {props={'Fusion'}},
    ["Detonator"]       = {props={'Fusion','Transfixion'}},
    ["Numbing Shot"]    = {props={'Induration','Detonation','Impaction'}},
    ["Last Stand"]      = {props={'Fusion','Reverberation'},aeonic={weapon="Fomalhaut",sc='Light'}},
    ["Coronach"]        = {props={'Darkness','Fragmentation'},relic=true},
    ["Wildfire"]        = {props={'Darkness','Gravitation'},empy=true},
    ["Trueflight"]      = {props={'Fragmentation','Scission'},mythic=true},
    ["Leaden Salute"]   = {props={'Gravitation','Transfixion'},mythic=true}
}
